# Generated by Django 5.1.6 on 2025-02-23 07:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_grade_alter_user_school_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='subjects',
        ),
    ]
