# Generated by Django 5.1.6 on 2025-02-23 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_alter_test_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='subjects/'),
        ),
    ]
